# Generated by Django 5.0.4 on 2024-04-10 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paster', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Вид декоративной штукатурки', 'verbose_name_plural': 'Виды декоративной штукатурки'},
        ),
        migrations.AlterModelOptions(
            name='decorativeplaster',
            options={'verbose_name': 'Декоративная штукатурка', 'verbose_name_plural': 'Декоративные штукатурки'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Тип декоративной штукатурки', 'verbose_name_plural': 'Типы декоративных штукатурок'},
        ),
        migrations.AddField(
            model_name='decorativeplaster',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decorativeplaster_category', to='paster.type', verbose_name='Вид'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Вид декоративной штукатурки'),
        ),
        migrations.AlterField(
            model_name='decorativeplaster',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decorativeplaster', to='paster.manufacturer', verbose_name='Производитель декоративной штукатурки'),
        ),
        migrations.AlterField(
            model_name='decorativeplaster',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decorativeplaster_type', to='paster.type', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='type',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='types', to='paster.category', verbose_name='Тип декоративной штукатурки'),
        ),
    ]
